### ISSUE TITLE
Scene doesn't change with more than one Scene accessory in the config.json

### ISSUE THREAD

**Issue by c-schulz-rd13** [codetheweb/homebridge-yamaha-scene#4]
I had the problem that if i used more than one accessory in the config.json the scene always switches to Scene 1.

Found out that the tag in the config.json should be "inital_scene" instead of "scene".

Can you please change that to "initial_scene" (there was also a typo i assume) and update the documentation as well?

Otherwise a great plugin, does exactly what I needed.

**Comment by codetheweb** [comment]
Sorry about that, fixed now in v0.1.1.
